[package]
name = "acpica"
version = "0.1.0"
authors = ["Lamb <contact@lambtowolf.me>"]
edition = "2018"

[dependencies]
cty = "0.2.1"

[build-dependencies]
bindgen = "0.52"
cc = { "version" = "1.0", features = ["parallel"] }

